const ANALOGUES = {
  UBER: 'UBER',
  UBER_EATS: 'UBER_EATS',
  AIRBNB: 'AIRBNB',
  TINDER: 'TINDER',
  LINKEDIN: 'LINKEDIN',
  FACEBOOK: 'FACEBOOK',
  INSTAGRAM: 'INSTAGRAM',
  TIKTOK: 'TIKTOK',
  KICKSTARTER: 'KICKSTARTER',
  AMAZON: 'AMAZON',
  WHATSAPP: 'WHATSAPP',
  YOUTUBE: 'YOUTUBE',
  NETFLIX: 'NETFLIX',
  SPOTIFY: 'SPOTIFY',
  MEDIUM: 'MEDIUM',
  ANOTHER: 'ANOTHER'
}

export default ANALOGUES