export { default as ANALOGUES } from './analogues'
export { default as INDUSTRIES } from './industries'
export { default as PLATFORMS } from './platforms'
export { default as ANALOG_MODELS } from './analogModels'
export { default as USD_TO_NOK } from './usdToNok'
export { default as MODEL_ESTIMATIONS } from './modelEstimations'
export { default as HOUR_RATE } from './hourRate'
export { default as COLLECTIONS } from './collections'
export { default as EMAIL_REGEX } from './emailRegEx'
export { BOOKING_MODULE_LINK, BOOKING_MODULE_LINK_DEV } from './appLinks'
export { default as STATISTIC_COLLECTIONS } from './statisticCollections'
export { CALCULATOR_FIELDS } from './calculatorFields'
