const INDUSTRIES = {
  E_COMMERCE: 'E_COMMERCE',
  SPORTS_AND_FITNESS: 'SPORTS_AND_FITNESS',
  MEDIA_AND_ENTERTAINMENT: 'MEDIA_AND_ENTERTAINMENT',
  FOOD: 'FOOD',
  EDUCATION_AND_TRAINING: 'EDUCATION_AND_TRAINING',
  HEALTHCARE: 'HEALTHCARE',
  AUTOMOTIVE: 'AUTOMOTIVE',
  FINANCE_BANKING_INSURANCE: 'FINANCE_BANKING_INSURANCE',
  TRAVEL: 'TRAVEL',
  REAL_ESTATE: 'REAL_ESTATE',
  MANUFACTURING: 'MANUFACTURING',
  LOGISTIC: 'LOGISTIC',
  AGRITECH: 'AGRITECH',
  NATURAL_RESOURCES: 'NATURAL_RESOURCES',
  GREEN_ENERGY: 'GREEN_ENERGY',
  INTERNET_OF_THINGS: 'INTERNET_OF_THINGS',
  ROBOTICS: 'ROBOTICS',
  KIDS: 'KIDS',
  SOCIAL_NETWORKING: 'SOCIAL_NETWORKING',
  DATING: 'DATING',
  PRODUCTIVITY: 'PRODUCTIVITY',
  ANOTHER: 'ANOTHER'
}

export default INDUSTRIES